FROM alpine:latest
MAINTAINER Abobakr
RUN apk add --no-cache maven
#RUN git clone https://github.com/spring-projects/spring-petclinic.git
RUN cp . /spring-petclinic
USERADD ali 
WORKDIR spring-petclinic
RUN mvn package
CMD ["mvn", "spring-boot:run"]
